version: "3.8"
services:
  mysql_db:
    build: ./db
    restart: always
    ports:
      - "3307:3306"
  
  
  backend:
    build: ./backend
    command: sh -c "sleep 10s; python app.py"
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      FLASK_ENV: development # remove if it causes issues
    depends_on:
      - mysql_db

  
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes: 
      - ./frontend:/user/src/app
    stdin_open: true
    tty: true
    environment:
      WATCHPACK_POLLING: true
    depends_on:
      - backend




